name: Pruebas unitarias y funcionales

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
        - 5432:5432

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4      

      - name: Wait for PostgreSQL to be ready
        run: until pg_isready -h localhost -p 5432; do sleep 1; done

      - name: Cargar esquema de la base de datos
        run: |
          psql -h localhost -U postgres -d testdb -f scripts.sql
        env:
          PGPASSWORD: postgres

      - name: Run tests
        run: |
          set -o pipefail
          psql -h localhost -U postgres -d testdb -f tests.sql 2>&1 | tee test_output.txt
          ERROR_LINES=$(grep -E "ERROR:" test_output.txt | cut -d':' -f1-3)
          echo "ERROR_LINES<<EOF" >> $GITHUB_ENV
          echo "$ERROR_LINES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV          
        env:
          PGPASSWORD: postgres

      - name: Notify status
        if: always()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_HEAD_REF: ${{ github.event.pull_request.head.ref }}
          GITHUB_SHA: ${{ github.sha }}
          ERROR_LINES: ${{ env.ERROR_LINES }}
        run: |
          if grep -q "ERROR:" test_output.txt; then
            exit 1
          fi          

      
